### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by Robgouw** [joelgrus/data-science-from-scratch#102]
I'm completely new to Python and tried this book for some exploration. I'm having issues with performing some code due to my ID E telling me that " No module named 'scratch.linear_algebra'" I have tried changing my PYTHONPATH to something like D:\Python\Library\Scratch and save the files but it still doesn't work. What else do I need to do.
Apologies if I needed more Python (or general programming) background to try this.

**Comment by mshearer0** [comment]
Where do you have the linear_algebra.py file? It needs to be in a sub-directory called scratch below a directory included in your path.

**Comment by Robgouw** [comment]
Now I have saved the Linear_algebra.py file in the folder called scratch. Those files just contains the code of that specific chapter.

**Comment by mshearer0** [comment]
Rob-data - yes, if for example you have ‘from scratch.module  import function’then it will look in the scratch sub directory for the file named module and in that file for the named function.

**Comment by Robgouw** [comment]
Should I change the name of the .py file to scratch.linear_algebra or would that not do the trick?

**Comment by mshearer0** [comment]
No, the file name shouldn’t need to change if it’s in the scratch directory. Your path should be to: D:\Python\Library\.

**Comment by Robgouw** [comment]
I tried to tidy it a bit and changed it to "D:\Python\Library\Modules: and this is how it looks: http://puu.sh/Hnimx/393a91efbb.png and it still gives me an Error. This is what de CMD says for PYTHONPATH: http://puu.sh/HnioR/a7fa658ff9.png (I read somewhere that you should check it over there). What am I doing wrong?

**Comment by dallabonagabriel** [comment]
Hi, sorry for the delay. I'm still quite new, I'm going to look for
what you instructed me to fix. Gratitude


Em seg., 8 de mar. de 2021 às 13:54, Rob <notifications@github.com>
escreveu:

**Comment by Robgouw** [comment]
I have looked up a bit more on modules and still don't know why it doesn't work but I have found a way to make it work. I have saved all the separate files and deleted the "scratch." from the python code and then it works. Thanks for trying to help!
