### ISSUE TITLE
Error in Whitespace Formatting in Chapter 2

### ISSUE THREAD

**Issue by iphyer** [joelgrus/data-science-from-scratch#11]
Sorry I encountered this in the book in  Chapter 2: 

>One	consequence	of	whitespace	formatting	is	that	it	can	be	hard	to	copy	and	paste	code
into	the	Python	shell.	For	example,	if	you	tried	to	paste	the	code:

>for	i	in	[1,	2,	3,	4,	5]:
				#	notice	the	blank	line
				print	i

into	the	ordinary	Python	shell,	you	would	get	a:
IndentationError:	expected	an	indented	block
because	the	interpreter	thinks	the	blank	line	signals	the	end	of	the	 for 	loop’s	block.

But it actually works in my Python Shell.

![1](https://cloud.githubusercontent.com/assets/1913891/8274923/b7b7b5fe-18cd-11e5-88f0-d42b0fb8ce84.png)

So I am confused whether it is right？

**Comment by joelgrus** [comment]
It gives an error on my machine, maybe the Chinese build of Python works differently?

**Comment by iphyer** [comment]
Yeap， And  I believe there maybe some other reasons。
See below：
![picture1](https://cloud.githubusercontent.com/assets/1913891/8276415/86d2ab4a-18e8-11e5-9ac3-565d566f465d.png)
