### ISSUE TITLE
Natural_language: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by gmrwvu** [joelgrus/data-science-from-scratch#13]
Looks like O'Reilly changed the div name from entry-content to article-body at
http://radar.oreilly.com/2010/06/what-is-data-science.html
Running natural_language_processing.py yields the NoneTyoe error.
To fix:
on line 48 of the program, change entry-content to article-body

**Comment by gomesfernanda** [comment]
@joelgrus please close the issue?

**Comment by MerlinSchaefer** [comment]
"article-body" now yields the same error.
As of now, the div name is "main-post-radar-content".
