### ISSUE TITLE
BackPropagation Algorithm

### ISSUE THREAD

**Issue by mkowoods** [joelgrus/data-science-from-scratch#2]
Hi,

It looks like in the algorithm for backprop the variable `output_layer` is used before it's defined in the `hidden_deltas` list comprehension. 

Also, do you have any tips for extending the algorithm for multi-layer networks?

**Comment by joelgrus** [comment]
Oops, you're right, it's not ever defined, I guess it should probably just be replaced with `network[-1]`.

My sense is that people usually stick with just one hidden layer, see, e.g.:

http://stats.stackexchange.com/questions/181/how-to-choose-the-number-of-hidden-layers-and-nodes-in-a-feedforward-neural-netw

**Comment by joelgrus** [comment]
OK, it's fixed now.  Thanks!
