### ISSUE TITLE
Web app is not working

### ISSUE THREAD

**Issue by QianXuX** [joelgrus/data-science-from-scratch#35]
When click on the linked provided in README, such error message showed up

---
404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: experiments/function-index/index.html
RequestId: AD1F5AB2228E5E80
HostId: Th07ZUUrIQtgVi8s0FD3zKMXu4KtfUSvbOpQaJmFXKMACJBDkTsm+GME6RZB6sSl9S49xXFxy0c=

---

**Comment by joelgrus** [comment]
oops, there was an error in my website configuration, it wasn't uploading all the files, should be fixed now. thanks for letting me know!
