### ISSUE TITLE
Simple Linear Regression / Stochastic Gradient Descent

### ISSUE THREAD

**Issue by paulaceccon** [joelgrus/data-science-from-scratch#65]
[SimpleLinearRegression.ipynb.zip](https://github.com/joelgrus/data-science-from-scratch/files/3158791/SimpleLinearRegression.ipynb.zip)
I'm trying the example provided in the chapter containing Simple Linear Regression using SGD, and the result does not converge. The value of the function keeps getting bigger, and the gradient direction is not changed. So, the first theta, randomly generated, is returned.

**Comment by joelgrus** [comment]
the error function in your notebook is the opposite of the one in the code:

https://github.com/joelgrus/data-science-from-scratch/blob/master/first-edition/code/simple_linear_regression.py#L11

which makes the gradient have the wrong sign
