### ISSUE TITLE
No images in repo

### ISSUE THREAD

**Issue by xmbn** [joelgrus/data-science-from-scratch#79]
There should be some images in the "im" folder but it's empty. This causes an error when importing inverse_normal_cdf from scratch. probability. It's looking for "various_normal_pdfs.png"

**Comment by joelgrus** [comment]
actually, it just wants the `im` directory to write images in it itself, but that's still bad.

just comment out the `plt.savefig` line, I'll do that in the repo too

**Comment by xmbn** [comment]
Thanks Joel. That makes sense. Once I viewed the code I realized it's not
just a library, there's code that runs in there when it's imported.
Commenting out works fine.
