### ISSUE TITLE
ModuleNotFoundError: No module named 'scratch'

### ISSUE THREAD

**Issue by m4ur0jr** [joelgrus/data-science-from-scratch#81]
I am not finding the module from scratch.probability import inverse_normal_cdf. I am using Spyder version 4.0 and reproducing the line of code as per the original code in the Data Science book from Zero. How can I move forward?

**Comment by jlxgcgcg** [comment]
see the "two notes" in the readme:

https://github.com/joelgrus/data-science-from-scratch#data-science-from-scratch

**Comment by Eddie2049** [comment]
Hi you could try something like this..

import os
path = "D:\\data_science_from_scratch" # here use specific path to your file
os.chdir(path)
from scratch.probability import inverse_normal_cdf
